name: Build Project
on:
  push:
    branches:
      - feature/ci-cd

jobs:
  build_project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x', 6.0.x]

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Setup Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/bin/Release/net5.0
      - name: Zip
        run: |
          # if zip is not found
          if [ ! -x "$(command -v zip)" ]; then
            sudo apt-get update && sudo apt-get install -y zip --no-install-recommends
          fi

          zip -r LSharp.zip ${{ github.workspace }}/bin/Release
      - name: Create New Release
        id: create_new_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          tag_name: v0.1.${{ github.run_number }}
          name: v0.1.${{ github.run_number }} Unstable L# Release.
          body: |
            # L# Unstable Release
            This is an automated released that contains the most recent changes added to L#.
            Such changes may include - Breaking and non-breaking features/bugfixes.
          draft: false
          prerelease: false
          files: |
            LSharp.zip

