name: Build Project
on:
  push:
    branches:
      - feature/ci-cd

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
